name: CI/CD Reto 3

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar ESLint
        run: npx eslint .  # Este paso falla si ESLint encuentra errores

  test:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar linter
        run: npm run lint
      
      - name: Ejecutar tests
        run: npm test

  docker-validation:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen Docker
        run: docker build -t whitewarlockmtj/reto3 .

      - name: Escanear imagen Docker con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: whitewarlockmtj/reto3
          format: table
          exit-code: 0
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          vuln-type: os,library
          skip-dirs: node_modules
          list-all-pkgs: false

  build-and-deploy:
    needs: docker-validation
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Autenticarse en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t whitewarlockmtj/reto3 .

      - name: Subir imagen a Docker Hub
        run: docker push whitewarlockmtj/reto3

      - name: Hacer deploy a WSL vía Serveo con contraseña
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            sudo docker pull whitewarlockmtj/reto3
            sudo docker stop reto3 || true
            sudo docker rm reto3 || true
            sudo docker run -d --name reto3 -p 3000:3000 whitewarlockmtj/reto3